version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    # Install gems, run rspec tests
    docker:
      - image: cimg/ruby:3.0.4-node
      - image: circleci/postgres:9.5-alpine
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: select gem for x86_64
          command: bundle lock --add-platform x86_64-linux
      - run:
          name: Database setup
          command: bundle exec rake db:test:prepare
      - run:
          name: rspec test
          command: bundle exec rspec
workflows:
  build-and-test:
    jobs:
      - test-ruby
