name: check-branch-name

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [(echo '${{github.head_ref}}' | sed -e 's@[^\/]@@g'| wc -c) -eq 3]; then
            exit 0
          else
            echo "::error:: ブランチ名は次のような形式である必要があります：<author>/<issue-number>/<title>"
            exit 1
          fi