name: reviewdog

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.rb'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./backend
      - name: Run RuboCop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile
          only_changed: true
          fail_on_error: true
